server:
  port: 8082 #启动端口
spring:
  application:
    name: moggpt

  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3307/mysql?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

      server:
        port: 8000

  redis:
    host: 127.0.0.1
    port: 6379
    password: yyliujbd001
    database: 1
    timeout: 30000

    # 日志文件路径
logging:
  file:
    name: /tmp/logs/${spring.application.name}/spring.log
